CREATE TABLE PROFESOR(
  NOMBRE VARCHAR(30) CONSTRAINT PRO_NOMBRE_NN NOT NULL
  ,SEXO CHAR(1) DEFAULT 'F' CONSTRAINT PRO_SEXO_CK CHECK(SEXO= 'F' OR SEXO= 'M')
  ,NOPROFESOR NUMERIC (6,0) CONSTRAINT PRO_NOPROFESOR_PK PRIMARY KEY
,SALARIO NUMERIC (6,2) DEFAULT 0 CONSTRAINT PRO_SALARIO_NN NOT NULL
  ,FECHADEINGRESO DATE DEFAULT SYSDATE CONSTRAINT PRO_FECHADEINGRESO_NN NOT NULL);


  CREATE TABLE ASIGNATURA(
    NOMBRE VARCHAR(30) 
    , CREDITOS NUMERIC (2,0) DEFAULT 5
    ,NOPROFESOR NUMERIC (6,0) 
    ,CLAVE NUMERIC (4,0) CONSTRAINT ASI_CLAVE_PK PRIMARY KEY
    ,FOREIGN KEY (NOPROFESOR) REFERENCES PROFESOR(NOPROFESOR));

    CREATE TABLE GRUPO(
        CLAVE NUMERIC (4,0)
        ,NOPROFESOR NUMERIC (6,0) DEFAULT 10
        ,NOGRUPO NUMERIC (3,0) CONSTRAINT GRU_NOGRUPO_PK PRIMARY KEY
        ,FOREIGN KEY (NOPROFESOR) REFERENCES PROFESOR(NOPROFESOR)
        ,FOREIGN KEY (CLAVE) REFERENCES ASIGNATURA(CLAVE));


/* NUEVO */
        GRANT CREATE SEQUENCE TO CAROL;
        CREATE SEQUENCE SEC_UNO;

        CREATE SEQUENCE SEC_TRIPLE
        START WITH 3
        INCREMENT BY 3
        MAXVALUE 30
        MINVALUE 3
        NOCYCLE
        NOCACHE;

        CREATE SEQUENCE SEC_PARES
        START WITH 2
        INCREMENT BY 2
        MAXVALUE 10
        MINVALUE 0
        CYCLE
        NOCACHE;


        CONN CAROL/123;

        CREATE TABLE ESTUDIANTE(
            NOMBRE VARCHAR(30) 
            ,NOCUENTA NUMERIC (6,0) 
            ,SEMESTRE NUMERIC (2,0) 
            ,GRUPO NUMERIC (2,0));

            ALTER TABLE ESTUDIANTE DROP CONSTRAINT EST_NOMBRE_NN;